#!/usr/bin/env bash
#a Bash script that Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
sudo apt -y install nginx
sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOL'
sudo nginx -s reload
