#!/usr/bin/env bash
#a Bash script that Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
sudo apt install nginx -y
sudo mkdir -p /var/www/html
sudo mkdir -p /var/www/html/errors
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/errors/404.html
sudo chown -R www-data:www-data /var/www/html
sudo chmod -R 755 /var/www/html
sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    error_page 404 /errors/404.html;
    location = /errors/404.html {
        internal;
    }
}
EOF'
sudo nginx -s reload
