#!/usr/bin/env bash
#install HAproxy

sudo apt-get update -y
sudo apt-get install haproxy -y

CONFIG_FILE="/etc/haproxy/haproxy.cfg"

CONFIG_BLOCK="
frontend http-in
    bind *:80
    default_backend mybackend

backend mybackend
    balance roundrobin
    server web-01 18.207.1.248:80 check
    server web-02 100.25.194.205:80 check
"
echo "$CONFIG_BLOCK" | sudo tee -a "$CONFIG_FILE" >/dev/null

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
