#!/usr/bin/env bash
# BackUP files

if [[ "$#" -ne 1 ]]; then
    exit 1
fi

DATE=$(date +%d-%m-%y)
file_name="backup.sql"
Arc_file="${DATE}.tar.gz"
DATABASE_NAME="tyrell_corp"

# Run mysqldump and handle errors
mysqldump -u root -p"$1" "$DATABASE_NAME" --single-transaction --quick --lock-tables=false >"${file_name}"

tar -czf "${Arc_file}" "${file_name}"
