#!/usr/bin/env bash
# Open the 80 port
if ! [ -x "$(command -v nginx)" ]; then
    sudo apt-get -y update
    sudo apt-get install -y nginx
fi
sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
curl -I 0:80 | grep "HTTP/1.1 200 OK" &>/dev/null
