#!/usr/bin/env bash
# Open the 80 port
if ! [ -x "$(command -v nginx)" ]; then
    apt-get update
    apt-get install -y nginx
fi
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
service nginx restart
