#!/usr/bin/env bash
# Descirption Of Process :
# ---------------------------------------------
# Displays the PID, along with the process name
# of processes whose name contain the word bash
pgrep -l bash
