#!/usr/bin/env bash
# Descirption Of Process :
# ---------------------------------------------
# - displays To infinity and beyond indefinitely.
# - In between each iteration of the loop, add a sleep 2
ID=$(pgrep -f "4-to_infinity_and_beyond")
if [ -n "$ID" ];
then
    pkill -f "4-to_infinity_and_beyond"
fi
