#!/usr/bin/env bash
# This script is displaying Numbers With Special Messages

n=1

while [ $n -lt 21 ];
do
    case $n in
        4)
            echo "$n"
            echo "bad luck from China"
            ;;
        9)
            echo "$n"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$n"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$n"
            ;;
    esac
    (( n++ ))
done
