#!/usr/bin/env bash
# The content of the current directory In a list format

for file in *; do
    if [[ ! "$file" == .* && -f "$file" ]]; then
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
