#!/usr/bin/env bash
# configures an Ubuntu server with the below requirements.
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.
ifconfig | awk '/inet (addr:)?([0-9]*\.){3}[0-9]*/ {gsub(/inet (addr:)?/, "", $2); print $2}'
