#!/usr/bin/env bash
# Run Nginx as nginx user
sed -i '1i\user nginx;' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo systemctl stop apache2 >/dev/null 2>&1
service nginx restart
